### PR TITLE
Maven updates part 2

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
See https://github.com/ome/ome-common-java/pull/25

### CODE REVIEW

**Comment by joshmoore** [comment]
Anything that needs to be added to the description re the imagej bump?

**Comment by rleigh-codelibre** [comment]
@joshmoore Not really, we did the corresponding bump in bioformats.git months ago, but this was left behind, so it's just catching up to the state in bioformats.

3fc421acb79 - Oct 2017

**Comment by joshmoore** [comment]
Will `imagej.version` eventually live _only_ in this repo?

**Comment by rleigh-codelibre** [comment]
@joshmoore I would expect so, once we've dropped it from bioformats and the tools.

**Comment by joshmoore** [comment]
Cheers.

**Pull request merged**
